#!/usr/bin/env python3
"""Regenerates the pages behind Classly links (open/ and 404.html).

    python3 tools/build_open_pages.py

https://thiemjason-work.site/classly/open/<screen> opens that screen in the app
when it is installed and the store otherwise (assets/open.js). Each screen the
app knows gets a real page, so link previews work; anything else under open/
(announcement ids, screens of newer versions) is served by 404.html, which runs
the same script. Keep SCREENS in step with AppDestination in the app repo
(docs/deep-links.md there).
"""
import html
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
BASE = 'https://thiemjason-work.site/classly'

# slug -> what the link opens, as shown in previews.
SCREENS = {
    '': 'Classly',
    'today': 'Today',
    'subjects': 'Subjects',
    'insights': 'Insights',
    'overview': 'Semester overview',
    'can-i-miss': 'Can I miss?',
    'planner': 'Academic Planner',
    'more': 'More',
    'calendar': 'Attendance Calendar',
    'reports': 'Attendance Reports',
    'add-subject': 'Add a subject',
    'import-timetable': 'Import your timetable',
    'notification-settings': 'Notification settings',
    'semester-backup': 'Semester Backup',
    'whats-new': "What's New",
    'setup-guide': 'Setup Guide',
    'announcements': 'News from the developer',
    'days-off': 'Days Off',
}


def page(title, url, status_note=''):
    heading = 'Open Classly' if title == 'Classly' else f'Open {title} in Classly'
    t = html.escape(heading)
    return f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{t}</title>
  <meta name="description" content="Classly keeps your attendance, timetable and deadlines in one calm, private place.">
  <meta name="theme-color" content="#F7F7F5" media="(prefers-color-scheme: light)">
  <meta name="theme-color" content="#121314" media="(prefers-color-scheme: dark)">
  <meta property="og:title" content="{t}">
  <meta property="og:description" content="Attendance, timetable and deadlines in one calm, private place.">
  <meta property="og:image" content="{BASE}/assets/classly-icon.png">
  <meta property="og:type" content="website">{f"""
  <meta property="og:url" content="{html.escape(url)}">""" if url else ''}
  <meta name="robots" content="noindex">
  <link rel="icon" type="image/png" href="/classly/assets/favicon.png">
  <link rel="apple-touch-icon" href="/classly/assets/apple-touch-icon.png">
  <link rel="stylesheet" href="/classly/assets/site.css">
  <style>
    .open-page {{ min-height: 100vh; display: grid; place-items: center; padding: 24px 16px; text-align: center; }}
    .open-card {{ max-width: 420px; }}
    .open-card img {{ border-radius: 22px; }}
    .open-card h1 {{ font-size: 1.6rem; margin: 18px 0 8px; }}
    .open-card p {{ margin: 0 0 22px; opacity: .75; }}
    .open-card .actions {{ display: flex; flex-direction: column; gap: 10px; }}
    .open-card .actions .btn {{ justify-content: center; }}
    .open-card .hint {{ font-size: .85rem; margin-top: 18px; }}
  </style>
</head>
<body>
<!-- Generated by tools/build_open_pages.py; edit that instead. -->
<main class="open-page">
  <div class="open-card">
    <img src="/classly/assets/classly-icon.png" alt="" width="88" height="88">
    <h1>{t}</h1>
    <p>Opening Classly… If nothing happens, use a button below.</p>
    <div class="actions">
      <a id="open-app" class="btn btn-ink" href="classly://open">Open in Classly</a>
      <a class="btn btn-line" href="https://apps.apple.com/app/id6760553317" rel="noopener">Download on the App Store</a>
      <a class="btn btn-line" href="https://play.google.com/store/apps/details?id=com.thiemjason.classattendance" rel="noopener">Get it on Google Play</a>
    </div>
    <p class="hint"><a href="/classly/">About Classly</a>{status_note}</p>
  </div>
</main>
<script src="/classly/assets/open.js"></script>
</body>
</html>
'''


def main():
    open_dir = ROOT / 'open'
    for slug, title in SCREENS.items():
        target = open_dir / slug / 'index.html' if slug else open_dir / 'index.html'
        target.parent.mkdir(parents=True, exist_ok=True)
        url = f'{BASE}/open/{slug}' if slug else f'{BASE}/open'
        target.write_text(page(title, url), encoding='utf-8')
    # GitHub Pages serves this for any missing path under /classly/, so
    # links to announcements or to screens of newer versions still work.
    (ROOT / '404.html').write_text(page('Classly', ''), encoding='utf-8')
    print(f'Wrote {len(SCREENS)} pages under open/ and 404.html')


if __name__ == '__main__':
    main()
